import sys
import numpy
import random

#Import methods
from reduction_techniques import srs_selection
from reduction_techniques import clc_selection
from reduction_techniques import mms_selection
from reduction_techniques import des_selection
from reduction_techniques import dom_selection
from reduction_techniques import phl_selection
from reduction_techniques import nrmd_selection
from reduction_techniques import psa_selection